name: d_store
description: "A new Flutter project."
 
publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.5
  get: ^4.6.6
  get_it: ^7.6.7
  flutter_bloc: ^8.1.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  iconsax: ^0.0.8
  go_router: ^13.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0




 
flutter:

  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/on_bording/
    - assets/images/login/
    - assets/images/signup/
    - assets/icons/
    - assets/icons/brands/
    - assets/logo/

  
   
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
      
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: assets/logo/logo.png

  android_12:  
    color: "#ffffff"
    color_dark: "#121212"
    image: assets/logo/icon.png

  web: false